# Generated by Django 2.2.4 on 2019-09-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
