# Generated by Django 2.2.4 on 2019-09-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializerApp', '0002_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
