# Generated by Django 2.2.4 on 2019-09-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializerApp', '0003_auto_20190905_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
    ]
