# Generated by Django 2.0 on 2019-10-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='note',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
